### PR TITLE
Fix capture page

### PR DESCRIPTION
**Pull request by AidanCaruso**
## Summary
Removes daisyui from capture page and tenatively restores buttons for testing of mocap code.

image

## References
closes #_insert number here_

### CODE REVIEW

**Comment by DanielBelmes** [comment]
We can also remove the daisyUI config and plugin from the two tailwind configs. it's probably causing tailwind loading issues too.
`etherealengine/packages/ui/tailwind.config.js`
`etherealengine/packages/client/tailwind.config.js`

**Comment by AidanCaruso** [comment]
> We can also remove the daisyUI config and plugin from the two tailwind configs. it's probably causing tailwind loading issues too. `etherealengine/packages/ui/tailwind.config.js` `etherealengine/packages/client/tailwind.config.js`

Yup, these have already been removed in a previous PR. There are no more references to daisyUI in the codebase after this PR.
Note in the first commit I experimentally added daisyUI back to the tailwind exports but reverted this in the next.

**Comment by DanielBelmes** [comment]
> > We can also remove the daisyUI config and plugin from the two tailwind configs. it's probably causing tailwind loading issues too. `etherealengine/packages/ui/tailwind.config.js` `etherealengine/packages/client/tailwind.config.js`
> 
> 
> 
> Yup, these have already been removed in a previous PR. There are no more references to daisyUI in the codebase after this PR.
> 
> Note in the first commit I experimentally added daisyUI back to the tailwind exports but reverted this in the next.

Oh weird maybe I had an old branch checked out when reviewing earlier.

**Comment by AidanCaruso** [comment]
> Oh weird maybe I had an old branch checked out when reviewing earlier.

Indeed, just double checked. 
image

**Comment by DanielBelmes** [comment]
> > Oh weird maybe I had an old branch checked out when reviewing earlier.
> 
> 
> 
> Indeed, just double checked. 
> 
> image
> 
> 
> 
> 
> 
> 

Sorry to make you check 🥲.

**Review by HexaField — APPROVED** [review]

**Pull request merged**
