### PR TITLE
Instancing component

### PR DESCRIPTION
**Pull request by dinomut1**
Adds Instancing component to engine. 

Three sampling modes: 
Scatter: instances are scattered onto the target surface based on UV
Vertices: one instance per vertex on target surface
Nodes: one instance per transform of children of root node

Two instancing modes:
Grass: generates instanced banners with custom shader
Mesh: instances provided mesh to sample points

Tests + UX polish forthcoming

Addresses first part of #6272

### CODE REVIEW

**Comment by NPatel10** [comment]
@dinomut1, I am not able to make instance of the grass at my end. If you can provide all the details necessary to produce grass it would be great for testing. Thanks.
SS1
SS

**Comment by dinomut1** [comment]
> @dinomut1, I am not able to make instance of the grass at my end. If you can provide all the details necessary to produce grass it would be great for testing. Thanks. SS1 SS

@NPatel10 I think the ground plane is too large. I have only tested it using Model nodes as the target surface.

**Comment by NPatel10** [comment]
@dinomut1, Above suggestions works, But now if I select spawn point it is giving me error suggesting there is no uvs. I think which is fine but after getting this error the component freezes and does not let me stage or restage anything.

**Comment by dinomut1** [comment]
> @dinomut1, Above suggestions works, But now if I select spawn point it is giving me error suggesting there is no uvs. I think which is fine but after getting this error the component freezes and does not let me stage or restage anything.

@NPatel10 Added stricter checks for the target surface options check

**Comment by NPatel10** [comment]
> @NPatel10 Added stricter checks for the target surface options check

This is fixed but it shows itself in the list and same problem occurs when selecting itself. And another one is the icon is not being showed in the hierarchy panel for instance node.

**Comment by dinomut1** [comment]
> > @NPatel10 Added stricter checks for the target surface options check
> 
> This is fixed but it shows itself in the list and same problem occurs when selecting itself. And another one is the icon is not being showed in the hierarchy panel for instance node.

@NPatel10 good finds. The icon not showing up in hierarchy is a problem I do not know how to fix. The other component I've made (Asset component) also has no icon in the hierarchy. Low priority

I will debug the selecting itself as target and freezing bug

**Review by NPatel10 — APPROVED** [review]

**Comment by NPatel10** [comment]
@dinomut1, I fixed the icon issue for instancing component.

**Pull request merged**
