### PR TITLE
IR-1996 Fix SaveAs

### PR DESCRIPTION
**Pull request by CITIZENDOT**
## References
closes #_insert number here_

### CODE REVIEW

**Comment by aditya-mitra** [comment]
Is this also closing this ticket - [Studio - Save As Errors and Unexpected behavior](https://tsu.atlassian.net/browse/IR-476) ?

**Comment by CITIZENDOT** [comment]
Actually it does! Just realised it now.

**Comment by CITIZENDOT** [comment]
It does. Thanks for pointing out!

**Comment by HexaField** [comment]
solved here https://github.com/EtherealEngine/etherealengine/pull/10144

**Pull request closed without merging**
