### PR TITLE
Support GLTF Authoring

### PR DESCRIPTION
**Pull request by HexaField**
## Summary

Adds editor control function implementations for GLTF, as well as the infrastructure for GLTF snapshots. Snapshots do not modify GLTF asset, as this requires a new custom loader for GLTF directly to ECS.

## Subtasks Checklist

- [x] Adds GLTFDocumentState and GLTFSnapshotState
- [x] Adds editor control function implementations and tests for GLTF, as well as immediate ECS updates
- [x] Fix NameComponent not updating maps upon changing name
- [x] Fixes studio publish
- [x] Suppresses annoying react test warnings
- [x] Removes unused files

## References
closes #_insert number here_

### CODE REVIEW

**Comment by DanielBelmes** [comment]
- Pressing delete on keyb crashes UI :( 
- adding new entities and saving is not working(Can edit existing entities)
- Save As crashes canvas(Never gets saved. 403s Then the editor tries to parse html response as json. Same errors as save as gltf was having so might just be a proper api save call.

**Comment by HexaField** [comment]
> * Pressing delete on keyb crashes UI :(
> * adding new entities and saving is not working(Can edit existing entities)
> * Save As crashes canvas(Never gets saved. 403s Then the editor tries to parse html response as json. Same errors as save as gltf was having so might just be a proper api save call.

The first issue is pre-existing, and the latter two I cannot reproduce on the latest commit.

**Comment by DanielBelmes** [comment]
> > * Pressing delete on keyb crashes UI :(
> 
> > * adding new entities and saving is not working(Can edit existing entities)
> 
> > * Save As crashes canvas(Never gets saved. 403s Then the editor tries to parse html response as json. Same errors as save as gltf was having so might just be a proper api save call.
> 
> 
> 
> The first issue is pre-existing, and the latter two I cannot reproduce on the latest commit.

I'll push to QAT again and test. It was as simple as add entity add component. Save. Refresh. Save as I'm impartial too

**Comment by HexaField** [comment]
> > > * Pressing delete on keyb crashes UI :(
> > 
> > 
> > > * adding new entities and saving is not working(Can edit existing entities)
> > 
> > 
> > > * Save As crashes canvas(Never gets saved. 403s Then the editor tries to parse html response as json. Same errors as save as gltf was having so might just be a proper api save call.
> > 
> > 
> > The first issue is pre-existing, and the latter two I cannot reproduce on the latest commit.
> 
> I'll push to QAT again and test. It was as simple as add entity add component. Save. Refresh. Save as I'm impartial too

Still can't replicate this

**Pull request merged**
