### PR TITLE
refactor: Update Primus initialization to include pathname in server URL

### PR DESCRIPTION
**Pull request by MoizAdnan**

### CODE REVIEW

**Review by HexaField — APPROVED** [review]

**Review by HexaField — CHANGES_REQUESTED** [review]
do we need to do this for instance server connections too?

**Comment by MoizAdnan** [comment]
> do we need to do this for instance server connections too?

I am not sure, how to check?

**Comment by HexaField** [comment]
> > do we need to do this for instance server connections too?
> 
> I am not sure, how to check?

Client connects here
https://github.com/EtherealEngine/etherealengine/blob/dev/packages/client-core/src/transports/SocketWebRTCClientFunctions.ts#L275

Instance server receives connection here
https://github.com/EtherealEngine/etherealengine/blob/dev/packages/instanceserver/src/channels.ts#L609

**Comment by MoizAdnan** [comment]
> > > do we need to do this for instance server connections too?
> > 
> > 
> > I am not sure, how to check?
> 
> Client connects here https://github.com/EtherealEngine/etherealengine/blob/dev/packages/client-core/src/transports/SocketWebRTCClientFunctions.ts#L275
> 
> Instance server receives connection here https://github.com/EtherealEngine/etherealengine/blob/dev/packages/instanceserver/src/channels.ts#L609

We looked into it, and we do not need pathName in instance server connections

**Review by hanzlamateen — APPROVED** [review]

**Review by HexaField — APPROVED** [review]

**Pull request merged**
