### PR TITLE
Material export fixes

### PR DESCRIPTION
**Pull request by dinomut1**
Fixes a few issues with saving and loading materials from .material.gltf files

### CODE REVIEW

**Review by JT00y — APPROVED** [review]

**Comment by HexaField** [comment]
@dinomut1 @JT00y @MichaelEstes hey all, could we take a look at this again and see if it still wroks / needs changes / is relevant?  thanks

**Review by HexaField — CHANGES_REQUESTED** [review]
I've tried exporting the apartment and it throws complains about MaterialNotFound

**Comment by DanielBelmes** [comment]
@dinomut1 @JT00y We have a lot of changes coming into materials from Aidan's work and Josh reported this didn't fix the issue. Can we get a review on the state of this and close it if it's not gonna be worked on?

**Comment by dinomut1** [comment]
Got these changes into prefab PR

**Pull request closed without merging**
