### PR TITLE
robust popover implementation

### PR DESCRIPTION
**Pull request by aditya-mitra**
## References

https://tsu.atlassian.net/browse/IR-2438
https://tsu.atlassian.net/browse/IR-2293

### CODE REVIEW

**Comment by CITIZENDOT** [comment]
https://github.com/EtherealEngine/etherealengine/assets/52322531/ea0d71f9-7ce1-4833-a4c1-41079fc89c0d

there's a white line appearing when ModelCompress popup (or) ImageCompress popup is opening. Not sure whether this is related to this PR.

**Comment by CITIZENDOT** [comment]
image

Tooltip is surrounded by a div with white background. It shouldn't be the case.

**Comment by CITIZENDOT** [comment]
https://github.com/EtherealEngine/etherealengine/assets/52322531/58cd0c39-e301-4732-ac28-2d0e84c0ab38

~when opening new context menu, a white bar is appearing across the scene. (This is happening with all new popovers)~

White bar issue went away after reinstalling node_modules, But another issue remains. Context menu is not closing after the Compress modal is opened. Ideally, it should be closed after `Compress` button is clicked.

**Comment by aditya-mitra** [comment]
> image
> 
> Tooltip is surrounded by a div with white background. It shouldn't be the case.

seems to working fine for me
image
can you try reinistalling the node modules?

**Review by CITIZENDOT — APPROVED** [review]

**Comment by SYBIOTE** [comment]
guys, popups for adding entity and components are broken , they popup at the wrong location

**Pull request merged**
