### PR TITLE
Default Prefabricated Components

### LINKED ISSUE #9291: Create Default Prefabs for Common Component Types
To replace components panel, we should create basic prefabs that have the correct configurations for common ECS usage.

- Model Component with Shadow, Envmap, LoopAnimation components
- Model Component with Collider set to Mesh mode for Mesh Colliders
- Particle Systems with better default values
...etc

These will be dragged and dropped into scene from Assets Panel instead of from the Components Tab

### PR DESCRIPTION
**Pull request by aditya-mitra**
## Summary

- add default component prefabs in scene assets panel
- ability drag and drop the component prefabs into the scene
- added 2 component prefabs

## References
closes #9291 

## QA Steps

https://github.com/EtherealEngine/etherealengine/assets/55396651/a199a23e-1f83-4aba-b54f-2d22594f8063

### CODE REVIEW

**Review by dinomut1 — CHANGES_REQUESTED** [review]
I cannot drag and drop these onto the scene hierarchy. Also, double click should create a prefab at the origin.

**Comment by aditya-mitra** [comment]
> I cannot drag and drop these onto the scene hierarchy. Also, double click should create a prefab at the origin.

added them!

https://github.com/EtherealEngine/etherealengine/assets/55396651/92a05070-4e1c-464b-a6df-8e80867dca6a

**Review by dinomut1 — CHANGES_REQUESTED** [review]
Need to debug: When an Animated Model is created, clicking on it in the hierarchy panel causes UI to crash
image

**Comment by HexaField** [comment]
closing in favour of https://github.com/EtherealEngine/etherealengine/pull/10047

**Comment by dinomut1** [comment]
We want to use this structure for defining the prefabs, let's just make sure this is up to date with dev and has all the up to date prefab definitions as outlined in the component doc

**Comment by dinomut1** [comment]
ok we're just making a new PR to handle this since Jiatong is taking this over

**Pull request closed without merging**
