### PR TITLE
File Browser: Fix Thumbnails Not Displaying for Files Not In Current Project

### PR DESCRIPTION
**Pull request by dinomut1**
Parses the project name of a given file from its path to correctly query static resources for its thumbnail

### CODE REVIEW

**Review by HexaField — CHANGES_REQUESTED** [review]
This won't work in multitenancy as project names are of the format `orgname/projectname`

**Comment by HexaField** [comment]
The file browser should already have the current directory's project name that can be passed down into the file grid component

**Comment by dinomut1** [comment]
> This won't work in multitenancy as project names are of the format `orgname/projectname`

Yes it will. Regexes don't strictly match from the beginning of a string unless you put a "^" at the start of it.

See https://regexr.com/82gik

**Comment by HexaField** [comment]
Except this is not the structure of MT

Screenshot from 2024-07-05 08-29-10

This is
Screenshot from 2024-07-05 08-28-35

And we want to capture `orgname/projectname` as the whole project name.

**Review by HexaField — APPROVED** [review]

**Comment by dinomut1** [comment]
Gotcha also better to not use regexes anyways

**Review by aditya-mitra — APPROVED** [review]

**Pull request merged**
