### PR TITLE
Rework GLTF State loader to use a UUID dictionary

### PR DESCRIPTION
**Pull request by HexaField**
## Summary

- [x] Adds a `GLTFNodeState` with `convertGltfToNodeDictionary` to help with GLTFState reactor logic
- [x] Adds `GLTFSnapshotAction.unload` action to include unloading scenes in event sourced state
- [x] Adds comprehensive tests for `GLTFState`
- [x] Rewrites tests for `EditorControlFunctions` to test GLTF data instead of resultant ECS state

## References
closes #_insert number here_

### CODE REVIEW

**Comment by DanielBelmes** [comment]
- New Reparenting bug(Any reparenting breaks. Hard to track whats wrong)
- Grouping breaks as well(was working on dev as of yesterday)
- Deleting still broken if you wanna try to fix it here

**Comment by HexaField** [comment]
blocked by https://github.com/EtherealEngine/etherealengine/pull/10170

**Review by DanielBelmes — APPROVED** [review]

**Review by DanielBelmes — CHANGES_REQUESTED** [review]
Saving not persisting sadly

**Review by DanielBelmes — COMMENTED** [review]
QA'd

**Pull request merged**
