### PR TITLE
Fix scene menu position

### PR DESCRIPTION
**Pull request by SYBIOTE**
This pull request fixes the position of the scene menu. Previously, the menu was positioned at the bottom of the element, but now it is positioned at the top. This change ensures that the menu is displayed correctly and improves the user experience.

in combination with #10691

### CODE REVIEW

**Review by hanzlamateen — CHANGES_REQUESTED** [review]
> https://github.com/theinfinitereality/eepro-multitenancy/pull/352#discussion_r1686384397

@SYBIOTE I dont see it being cut off. Can you ellaboratre it further
image

Moreover, since this same sceneItem is being used in console, and in console we are opening all context menus to bottom right. Therefore for if in studio its required to be on top, then that can be handled through some prop?

**Comment by SYBIOTE** [comment]
it cuts off on smaller screens, like this

**Comment by hanzlamateen** [comment]
@SYBIOTE I can't access the image you referred. Maybe you can provide a property in scene item through which both these behaviors can be supported.

**Comment by SYBIOTE** [comment]
this does not seem relevant anymore, closing the PR

**Pull request closed without merging**
