### PR TITLE
Use component's true values in the node editor

### PR DESCRIPTION
**Pull request by CITIZENDOT**
## References
closes #_insert number here_

### CODE REVIEW

**Review by HexaField — CHANGES_REQUESTED** [review]
why are we removing local/world support?

**Comment by CITIZENDOT** [comment]
Accounted for transform space when any of the transforms changed!

**Comment by HexaField** [comment]
duplicate work going on here https://github.com/EtherealEngine/etherealengine/pull/10166

**Comment by DanielBelmes** [comment]
I'm not entirely sure why but with your changes when adding a child to a parent. Your useEffect is moving the child and parents position on any change or even reselect.

**Pull request closed without merging**
