### PR TITLE
IR-2555: Add controls for alpha masking and custom uv offset + scaling for Video Component

### PR DESCRIPTION
**Pull request by dinomut1**
Closes https://tsu.atlassian.net/browse/IR-2555

### CODE REVIEW

**Comment by AidanCaruso** [comment]
In testing with the sample video in the default project, it appears the video texture value is always null resulting in the shader color being red. The media component does have the resource url set, on dev it seems to render properly.
image

**Comment by DanielBelmes** [comment]
image
Updates no longer red and alpha works

**Comment by dinomut1** [comment]
I'm seeing a problem with our implementation for looping videos. One of our reactors is running every frame and repeatedly setting the image of the video, which causes the video texture to have a new "version" for every frame. When I changed the reactor not to happen every frame videos don't loop anymore

**Comment by dinomut1** [comment]
ok i'm just merging this in after convo with daniel

**Review by DanielBelmes — COMMENTED** [review]
Post approval

**Pull request merged**
