### PR TITLE
IR-2721: Zendesk integration

### PR DESCRIPTION
**Pull request by jose-galvan**
## Summary

Zendesk widget integration

## References
closes #_insert number here_

## QA Steps

- Set up a Zendesk key in your environment file
- Go to the console
- it shouldn't be displayed when you are not authenticated
- Log in
- It should display a button in the lower right corner which opens a messaging window.  
- This functionality is only for authenticated users

### CODE REVIEW

**Comment by hanzlamateen** [comment]
How can I test this? Can you please provide steps?

**Comment by jose-galvan** [comment]
> How can I test this? Can you please provide steps?

@hanzlamateen, I updated the QA steps.

**Review by hanzlamateen — CHANGES_REQUESTED** [review]
Overall seems to be working fine. Though:

1. Need to pass `VITE_ZENDESK_ENABLED` & `VITE_ZENDESK_KEY` in all files as done in following PR
https://github.com/EtherealEngine/etherealengine/pull/10426
2. @HexaField should this be done in core engine or a new project/module for zendesk?

**Comment by jose-galvan** [comment]
> Overall seems to be working fine. Though:
> 
> 1. Need to pass `VITE_ZENDESK_ENABLED` & `VITE_ZENDESK_KEY` in all files as done in following PR
>    [Added VITE_FEATHERS_STORE_KEY to Docker builds #10426](https://github.com/EtherealEngine/etherealengine/pull/10426)
> 2. @HexaField should this be done in core engine or a new project/module for zendesk?

Done

**Comment by HexaField** [comment]
This is fine to include in the core engine for now

**Review by hanzlamateen — APPROVED** [review]

**Pull request merged**
